In [1]:
   
import math
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
#from tensorflow.python.framework import ops from cnn_utils import *

from math import pi
import itertools

%matplotlib inline

with tf.Session() as sess:
    hello = tf.constant('Hello, TensorFlow!')
    print(sess.run(hello))


/Users/home/code/tensorflow/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


b'Hello, TensorFlow!'


In [2]:
class Vertex:
    """a polar coordinate vertex of unit length"""
    def __init__(self, index):
        self.index = index
        self.theta = tf.get_variable("theta" + str(index), [1], initializer=tf.constant_initializer(np.random.random_sample() * pi))
        self.phi = tf.get_variable("phi" + str(index), [1], initializer=tf.constant_initializer(np.random.random_sample() * 2 * pi))
        sin_theta = tf.sin(self.theta)
        self.x = tf.multiply(sin_theta, tf.cos(self.phi) , name='x' + str(self.index))
        self.y = tf.multiply(sin_theta, tf.sin(self.phi) , name='y' + str(self.index))
        self.z = tf.cos(self.theta, name='z' + str(self.index))
        self.xyz = tf.concat([self.x, self.y, self.z], axis=0)
    
    def distSquared( vertex1, vertex2 ):
        
        return 


def make_vertextes( n_vertexes ):
    vertexes = []
    for i in range(n_vertexes):
        vertexes.append( Vertex(i) )
    return vertexes

def makePairsInverseDistance( vertexes ):
    list = []
    for pair in itertools.combinations(vertexes, 2):
        list.append( 1 / tf.norm(pair[0].xyz-pair[1].xyz))
    return tf.add_n(list)    



In [66]:
n_vertexes = 5 # 32

tf.reset_default_graph()
verts = make_vertextes(n_vertexes)
potential = makePairsInverseDistance(verts)
optimizer = tf.train.GradientDescentOptimizer( learning_rate=1e-1 ).minimize(potential)

#print([v.xyz for v in verts])
allPositions = tf.stack([v.xyz for v in verts])

NUM_THREADS = 2
 
with tf.Session(config=tf.ConfigProto( intra_op_parallelism_threads=NUM_THREADS)) as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(500):
        if(i % 10 == 0):
            _ , p = sess.run([optimizer, potential] )
            print( str(i) + ' ' + str(p) )
        else:
            sess.run( optimizer )  
         
    pos = sess.run(allPositions)    
    print(pos)
    

0 10.5842
10 6.50263
20 6.47734
30 6.47564
40 6.47534
50 6.47519
60 6.47507
70 6.47499
80 6.47492
90 6.47486
100 6.47482
110 6.47479
120 6.47476
130 6.47475
140 6.47473
150 6.47472
160 6.47471
170 6.47471
180 6.4747
190 6.4747
200 6.4747
210 6.4747
220 6.4747
230 6.47469
240 6.47469
250 6.47469
260 6.47469
270 6.47469
280 6.47469
290 6.47469
300 6.47469
310 6.47469
320 6.47469
330 6.47469
340 6.47469
350 6.47469
360 6.47469
370 6.47469
380 6.47469
390 6.47469
400 6.47469
410 6.47469
420 6.47469
430 6.47469
440 6.47469
450 6.47469
460 6.47469
470 6.47469
480 6.47469
490 6.47469
[[ 0.47222146 -0.83064699 -0.29501268]
 [-0.47227982  0.83061755  0.29500201]
 [-0.7312479  -0.18229976 -0.6573    ]
 [-0.060554   -0.36446497  0.92924619]
 [ 0.79187512  0.54679567 -0.27193439]]


In [67]:
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from scipy.spatial import ConvexHull

 
hull = ConvexHull(pos)


# https://github.com/jovyan/pythreejs
from pythreejs import *
import numpy as np
from IPython.display import display

vertices = pos

faces = hull.simplices

 
cubeGeometry = PlainGeometry(vertices=vertices, faces=faces)

myobjectCube = Mesh(geometry=cubeGeometry, material = LambertMaterial(color='#aaaaaa'))
cCube = PerspectiveCamera(position=[4, 4, 4], fov=20,
                      children=[DirectionalLight(color='#555555', position=[30, 30, 30], intensity=1.5)])
sceneCube = Scene(children=[myobjectCube, AmbientLight(color='#ffffff')])

rendererCube = Renderer(camera=cCube, background='black', background_opacity=1,
                        scene = sceneCube, controls=[OrbitControls(controlling=cCube)])

myobjectCube.material.wireframe = True

display(rendererCube)

Renderer(background_opacity=1.0, camera=PerspectiveCamera(children=[DirectionalLight(color='#555555', intensity=1.5, position=[30.0, 30.0, 30.0], scale=[1.0, 1.0, 1.0], up=[0.0, 1.0, 0.0])], fov=20.0, position=[4.0, 4.0, 4.0], scale=[1.0, 1.0, 1.0], up=[0.0, 1.0, 0.0]), controls=[OrbitControls(controlling=PerspectiveCamera(children=[DirectionalLight(color='#555555', intensity=1.5, position=[30.0, 30.0, 30.0], scale=[1.0, 1.0, 1.0], up=[0.0, 1.0, 0.0])], fov=20.0, position=[4.0, 4.0, 4.0], scale=[1.0, 1.0, 1.0], up=[0.0, 1.0, 0.0]), target=[0.0, 0.0, 0.0])], effect=None, scene=Scene(children=[Mesh(geometry=PlainGeometry(faces=array([[0, 4, 2],
       [3, 0, 2],
       [3, 0, 4],
       [1, 4, 2],
       [1, 3, 2],
       [1, 3, 4]], dtype=uint32), vertices=array([[ 0.47222146, -0.83064699, -0.29501268],
       [-0.47227982,  0.83061755,  0.29500201],
       [-0.7312479 , -0.18229976, -0.6573    ],
       [-0.060554  , -0.36446497,  0.92924619],
       [ 0.79187512,  0.54679567, -0.27193439]], dtype=float32)), material=LambertMaterial(color='#aaaaaa', envMap=None, lightMap=None, map=None, specularMap=None, wireframe=True), position=[0.0, 0.0, 0.0], scale=[1.0, 1.0, 1.0], up=[0.0, 1.0, 0.0]), AmbientLight(color='#ffffff', position=[0.0, 0.0, 0.0], scale=[1.0, 1.0, 1.0], up=[0.0, 1.0, 0.0])], position=[0.0, 0.0, 0.0], scale=[1.0, 1.0, 1.0], up=[0.0, 1.0, 0.0]))

()

Todo:
1. fix face normals, https://github.com/mrdoob/three.js/blob/dev/src/core/Geometry.js computeFaceNormals
cubeGeometry.faceNormals

2. edge stats bar chart
3. variable learning rate and auto termination on converge
4. seperate setup from converging loop so can run multiple if doesn't converge